<?php

return [
    'owner' => env('BRAND_OWNER', 'DevRock'),
    'url' => env('BRAND_URL', ''),
    'mark' => env('BRAND_MARK', '//'),
    'logo' => env('BRAND_LOGO', ''),
    'start_year' => (int) env('BRAND_START_YEAR', 2022),
    'dashboard_title' => env('BRAND_DASHBOARD_TITLE', 'Your infrastructure, without the noise.'),
    'dashboard_subtitle' => env('BRAND_DASHBOARD_SUBTITLE', 'Welcome back, {username}.'),
    'dashboard_image' => env('BRAND_DASHBOARD_IMAGE', ''),
    'theme_preset' => env('BRAND_THEME_PRESET', 'makima'),
    'accent' => env('BRAND_ACCENT', '#c94f59'),
    'glass_strength' => (int) env('BRAND_GLASS_STRENGTH', 18),
    'card_radius' => (int) env('BRAND_CARD_RADIUS', 12),
    'motion_enabled' => (bool) env('BRAND_MOTION_ENABLED', true),
    'login_media' => env('BRAND_LOGIN_MEDIA', ''),
    'login_title' => env('BRAND_LOGIN_TITLE', 'Server control.'),
    'login_subtitle' => env('BRAND_LOGIN_SUBTITLE', 'Use your account.'),
    'console_background' => env('BRAND_CONSOLE_BACKGROUND', ''),
    'console_background_opacity' => (int) env('BRAND_CONSOLE_BACKGROUND_OPACITY', 18),
    'console_font_size' => (int) env('BRAND_CONSOLE_FONT_SIZE', 12),
    'console_scanlines' => (bool) env('BRAND_CONSOLE_SCANLINES', false),
    'status_enabled' => (bool) env('BRAND_STATUS_ENABLED', true),
    'status_title' => env('BRAND_STATUS_TITLE', 'Systems operational'),
    'status_message' => env('BRAND_STATUS_MESSAGE', 'Infrastructure is online and operating normally.'),
    'status_show_nodes' => (bool) env('BRAND_STATUS_SHOW_NODES', true),
    'status_node_mode' => env('BRAND_STATUS_NODE_MODE', 'all'),
    'announcement_enabled' => (bool) env('BRAND_ANNOUNCEMENT_ENABLED', false),
    'announcement_message' => env('BRAND_ANNOUNCEMENT_MESSAGE', ''),
    'announcement_type' => env('BRAND_ANNOUNCEMENT_TYPE', 'notice'),
    'announcement_link' => env('BRAND_ANNOUNCEMENT_LINK', ''),
];
